export interface StoreItemsModel {
  id: string;
  name: string;
  description: string;
  suggestedPrice: number;
  actualPrice: number;
  discountPrice: number;
  imageUrl: string;
}

export const StoreItems: StoreItemsModel[] = [
  {
    id: "cat-1",
    name: "Smart Watch",
    description: "This is Smart Watch a description for item 1",
    suggestedPrice: 10,
    actualPrice: 8,
    discountPrice: 2,
    imageUrl: "/a1.png",
  },
  {
    id: "cat-2",
    name: "Voltas AC",
    description: "This is a TATA Product",
    suggestedPrice: 20,
    actualPrice: 16,
    discountPrice: 4,
    imageUrl: "/ac1.png",
  },
  {
    id: "cat-3",
    name: "Haier AC",
    description: "This is a Haeir Product",
    suggestedPrice: 30,
    actualPrice: 24,
    discountPrice: 6,
    imageUrl: "/ac2.png",
  },
  {
    id: "cat-4",
    name: "Samsung AC",
    description: "This is a Samsung Product",
    suggestedPrice: 40,
    actualPrice: 32,
    discountPrice: 8,
    imageUrl: "/ac3.png",
  },
  {
    id: "cat-5",
    name: "ADA AC",
    description: "This is a AD Product",
    suggestedPrice: 50,
    actualPrice: 40,
    discountPrice: 10,
    imageUrl: "/ac4.png",
  },
  {
    id: "cat-6",
    name: "Apple Smart watch",
    description: "This is a Apple product",
    suggestedPrice: 60,
    actualPrice: 48,
    discountPrice: 12,
    imageUrl: "/apple.png",
  },
  {
    id: "cat-7",
    name: "Haeir Washing machine",
    description: "This is Haeir Washing machine",
    suggestedPrice: 70,
    actualPrice: 56,
    discountPrice: 14,
    imageUrl: "/item1.png",
  },
  {
    id: "cat-8",
    name: "LG Washing machine",
    description: "This is a LG Washing machine",
    suggestedPrice: 80,
    actualPrice: 64,
    discountPrice: 16,
    imageUrl: "/item2.png",
  },
  {
    id: "cat-9",
    name: "One plus",
    description: "This is a description for item 9",
    suggestedPrice: 90,
    actualPrice: 72,
    discountPrice: 18,
    imageUrl: "/tv4.png",
  },
  {
    id: "cat-10",
    name: "Bosch",
    description: "This is a description for Bosch",
    suggestedPrice: 100,
    actualPrice: 80,
    discountPrice: 20,
    imageUrl: "/item3.png",
  },
  {
    id: "cat-11",
    name: "Korting Washing machine",
    description: "This is for Korting Washing machine",
    suggestedPrice: 110,
    actualPrice: 88,
    discountPrice: 22,
    imageUrl: "/item4.png",
  },
  {
    id: "cat-12",
    name: "Sony",
    description: "This is a description for SOny tv",
    suggestedPrice: 120,
    actualPrice: 96,
    discountPrice: 24,
    imageUrl: "/tv4.png",
  },
  {
    id: "cat-13",
    name: "Phone",
    description: "This is a description for Phone",
    suggestedPrice: 130,
    actualPrice: 104,
    discountPrice: 26,
    imageUrl: "/phone1.png",
  },
  {
    id: "cat-14",
    name: "Sony",
    description: "This is a description for Sony",
    suggestedPrice: 140,
    actualPrice: 112,
    discountPrice: 28,
    imageUrl: "/phone2.png",
  },
  {
    id: "cat-15",
    name: "Moto 3",
    description: "This is a description for moto phone3",
    suggestedPrice: 150,
    actualPrice: 120,
    discountPrice: 30,
    imageUrl: "/phone3.png",
  },
  {
    id: "cat-16",
    name: "ASUS",
    description: "This is a description for ASUS",
    suggestedPrice: 160,
    actualPrice: 128,
    discountPrice: 32,
    imageUrl: "/phone5.png",
  },
  {
    id: "cat-17",
    name: "LG Super screen",
    description: "This is a description for LG Super screen",
    suggestedPrice: 170,
    actualPrice: 136,
    discountPrice: 34,
    imageUrl: "/tv2.png",
  },
  {
    id: "cat-18",
    name: "LG Tab",
    description: "This is a description for tab 18",
    suggestedPrice: 180,
    actualPrice: 144,
    discountPrice: 36,
    imageUrl: "/tab2.png",
  },
  {
    id: "cat-19",
    name: "MAC 19",
    description: "This is a description for MAC TAB 19",
    suggestedPrice: 190,
    actualPrice: 152,
    discountPrice: 38,
    imageUrl: "/tab2.png",
  },
  {
    id: "cat-20",
    name: "Samsung 20",
    description: "This is a description for Samsung 20",
    suggestedPrice: 200,
    actualPrice: 160,
    discountPrice: 40,
    imageUrl: "/tv1.png",
  },
];
